services:
  mqtt-sub:
    build: .
    container_name: mqtt-sub
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mqtt-broker
      - barramento-de-eventos
    networks:
      - smartfarm-network
      
networks:
  smartfarm-network:
    external: true